import OBJECTS from './objects';
import SPEED from './tank';

const TYPE = {
  BASIC: 'basic',
  FAST: 'fast',
  POWER: 'power',
  ARMORED: 'armored',
};

const TYPE_ORDER = [
  TYPE.BASIC,
  TYPE.FAST,
  TYPE.POWER,
  TYPE.ARMORED,
];

const POSITION = [
  [-96, 96],
  [0, 96],
  [96, 96],
];

const MOVEMENT_SPEED = [SPEED.SLOW, SPEED.FAST, SPEED.SLOW, SPEED.SLOW];

const PROJECTILE_SPEED = [SPEED.SLOW, SPEED.SLOW, SPEED.FAST, SPEED.SLOW];

const PROJECTILES_NUMBER = [1, 1, 1, 1];

const ARMOR_STRENGTH = [0, 0, 0, 3];

const BONUS_ORDER = [
  OBJECTS.BONUS.HELMET,
  OBJECTS.BONUS.TIMER,
  OBJECTS.BONUS.SHOWEL,
  OBJECTS.BONUS.STAR,
  OBJECTS.BONUS.GRENADE,
  OBJECTS.BONUS.TANK,
  OBJECTS.BONUS.STAR,
  OBJECTS.BONUS.GRENADE,
];

const BONUS_CARRIER = {
  '3': true,
  '10': true,
  '17': true,
};

export default {
  ARMOR_STRENGTH,
  BONUS_CARRIER,
  BONUS_ORDER,
  MOVEMENT_SPEED,
  POSITION,
  PROJECTILE_SPEED,
  PROJECTILES_NUMBER,
  TYPE_ORDER,
};
