import PROJECTILE from './projectile';
import TANK from './tank';

const TYPE = {
  BASIC: 'p-basic',
  DOUBLE_SHOT: 'p-double',
  FAST_SHOT: 'p-fast',
  POWER_SHOT: 'p-power',
};

const TYPE_ORDER = [
  TYPE.BASIC,
  TYPE.FAST_SHOT,
  TYPE.DOUBLE_SHOT,
  TYPE.POWER_SHOT,
];

const POSITION = [
  [-32, -96],
  [32, -96],
];

const MOVEMENT_SPEED = [TANK.SPEED.NORMAL, TANK.SPEED.NORMAL, TANK.SPEED.NORMAL, TANK.SPEED.NORMAL];

const PROJECTILE_SPEED = [TANK.SPEED.SLOW, TANK.SPEED.FAST, TANK.SPEED.FAST, TANK.SPEED.FAST];

const PROJECTILE_POWER = [
  PROJECTILE.POWER.HALF,
  PROJECTILE.POWER.HALF,
  PROJECTILE.POWER.HALF,
  PROJECTILE.POWER.FULL,
];

const PROJECTILES_NUMBER = [1, 1, 2, 2];

const SHIELD_TIMEOUT = {
  SPAWN: 120,
  BONUS: 600,
};

const IMMOBILITY_TIMEOUT = 192;

const COLORS_ORDER = [
  TANK.COLORS.YELLOW,
  TANK.COLORS.GREEN,
];

export default {
  COLORS_ORDER,
  IMMOBILITY_TIMEOUT,
  MOVEMENT_SPEED,
  POSITION,
  PROJECTILE_POWER,
  PROJECTILE_SPEED,
  PROJECTILES_NUMBER,
  SHIELD_TIMEOUT,
  TYPE,
  TYPE_ORDER,
};
