import OBJECTS from './objects';
import LAYOUT from './layout';

const PARENT = {
  PLAYER: 'player',
  ENEMY: 'enemy',
};

const SIZE = 4;

const COLLISION_SHIFT = SIZE / 2;

const COLLISION_POINTS = [
  [-COLLISION_SHIFT, COLLISION_SHIFT],
  [COLLISION_SHIFT, COLLISION_SHIFT],
];

const POSITION_CONSTRAINT = (LAYOUT.MAP_SIZE - SIZE) / 2;

const POWER = {
  HALF: 1,
  FULL: 2,
};

const POWER_NEEDED_TO_DAMAGE = {
  [OBJECTS.BLOCK.BRICK]: POWER.HALF,
  [OBJECTS.BLOCK.STEEL]: POWER.FULL,
};

export default {
  COLLISION_POINTS,
  COLLISION_SHIFT,
  PARENT,
  POSITION_CONSTRAINT,
  POWER,
  POWER_NEEDED_TO_DAMAGE,
  SIZE,
};
