import { COLORS } from '../constants';

export default function steel() {
  const canvas = document.createElement('canvas');
  canvas.width = 16;
  canvas.height = 16;
  const ctx = canvas.getContext('2d');
  ctx.imageSmoothingEnabled = false;
  ctx.fillStyle = COLORS['30'];
  ctx.fillRect(0, 0, canvas.width, canvas.height);
  ctx.beginPath();
  ctx.moveTo(16, 0);
  ctx.lineTo(0, 0);
  ctx.lineTo(0, 16);
  ctx.lineTo(1, 16);
  ctx.lineTo(1, 15);
  ctx.lineTo(2, 15);
  ctx.lineTo(2, 14);
  ctx.lineTo(3, 14);
  ctx.lineTo(3, 13);
  ctx.lineTo(4, 13);
  ctx.lineTo(4, 4);
  ctx.lineTo(13, 4);
  ctx.lineTo(13, 3);
  ctx.lineTo(14, 3);
  ctx.lineTo(14, 2);
  ctx.lineTo(15, 2);
  ctx.lineTo(15, 1);
  ctx.lineTo(16, 1);
  ctx.closePath();
  ctx.fillStyle = COLORS['10'];
  ctx.fill();
  ctx.beginPath();
  ctx.moveTo(16, 16);
  ctx.lineTo(1, 16);
  ctx.lineTo(1, 15);
  ctx.lineTo(2, 15);
  ctx.lineTo(2, 14);
  ctx.lineTo(3, 14);
  ctx.lineTo(3, 13);
  ctx.lineTo(4, 13);
  ctx.lineTo(4, 12);
  ctx.lineTo(12, 12);
  ctx.lineTo(12, 4);
  ctx.lineTo(13, 3);
  ctx.lineTo(14, 3);
  ctx.lineTo(14, 2);
  ctx.lineTo(15, 2);
  ctx.lineTo(15, 1);
  ctx.lineTo(16, 1);
  ctx.closePath();
  ctx.fillStyle = COLORS['00'];
  ctx.fill();
  return canvas;
}
